POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXIyIiwiaWQiOiI2MzA4YTkxN2U1YjljOTg5MTFiMjVlYzgiLCJpYXQiOjE2NjE1MTIwOTh9.zfl4Fj-SghZG7ehayiLJYnORUNjU1ivocFGsDxc1Rs0

    {
        "title": "New blog",
        "author": "Mikki Hiiri",
        "url": "...",
        "likes": 11,
        "userId": "6308a917e5b9c98911b25ec8"
    }