POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer 

    {
        "title": "Token2",
        "author": "Minni Hiiri",
        "url": "...",
        "likes": 15,
        "userId": "6305e3e42b37b1e3f90c5065"
    }